const affirmations = [
  "I am the architect of my life. I build its foundation and choose its contents.",
  "I possess the qualities needed to be extremely successful.",
  "My body is healthy; my mind is brilliant; my soul is tranquil.",
  "I have been given endless talents which I begin to utilize today.",
  "I am courageous and I stand up for myself.",
  "My thoughts are filled with positivity and my life is plentiful with prosperity.",
  "I acknowledge my own self-worth; my confidence is soaring.",
  "Everything that is happening now is happening for my ultimate good.",
  "I am a powerhouse; I am indestructible.",
  "Though these times are difficult, they are only a short phase of life.",
  "My future is an ideal projection of what I envision now.",
  "My efforts are being supported by the universe; my dreams manifest into reality.",
  "I radiate beauty, charm, and grace.",
  "I am conquering my illness; I am defeating it steadily each day.",
  "My obstacles are moving out of my way; my path is carved towards greatness.",
  "I wake up today with strength in my heart and clarity in my mind.",
  "My fears of tomorrow are simply melting away.",
  "I am at peace with all that has happened, is happening, and will happen.",
  "My nature is Divine; I am a spiritual being.",
  "My life is just beginning. The best is yet to come.",
  "I am becoming the best version of myself with every passing day.",
  "I have everything I need to face any obstacle that comes my way.",
  "Abundance flows freely through me and into every area of my life.",
  "I choose to be kind to myself and others. My compassion is infinite.",
  "I release all doubts and embrace the limitless potential within me.",
  "Every challenge I face is an opportunity to grow and improve.",
  "I am worthy of all the good things that happen in my life.",
  "I trust the process of life. Good things take time, and mine are coming.",
  "I attract success and prosperity with all of my ideas.",
  "I love myself deeply and unconditionally.",
  "I have the power to change my story. I am writing a masterpiece.",
  "My potential to succeed is infinite. I will not give up.",
  "I deserve to be happy and I allow myself to feel that joy fully.",
  "I am grateful for the abundance that I have and the abundance on its way.",
  "I stand in my power. No one can dim the light that shines from within me.",
  "I am resilient. I bounce back stronger every time I am knocked down.",
  "My mind is clear and focused. I accomplish great things with ease.",
  "I am a magnet for miracles. They flow to me constantly.",
  "I breathe in confidence and breathe out fear.",
  "Today I abandon old habits and take up new, more positive ones.",
  "I have the strength to make my dreams come true.",
  "I believe in my ability to unlock the way and set myself free.",
  "I commit to always growing and becoming a better me.",
  "My past does not define me. Today I create my future.",
  "I radiate positive energy and it returns to me multiplied.",
  "I am unstoppable. There is nothing that can hold back my greatness.",
  "I choose joy, growth, and transformation every single day.",
  "I am enough, exactly as I am right now, in this moment.",
  "Success is not a destination — it is my daily practice.",
  "I trust myself completely. My intuition is my guide.",
  "I create positive change in the world simply by showing up fully.",
  "My heart is open. Love flows in and out of me effortlessly.",
  "I am disciplined, persistent, and consistent in all that I do.",
  "I celebrate how far I have come while reaching higher every day.",
  "The universe conspires in my favor. Everything aligns for my good.",
  "I have unlimited capacity to learn, grow, and transform.",
  "I forgive myself for past mistakes and move forward with grace.",
  "My voice matters. I speak my truth with confidence and clarity.",
  "I am the energy I put out. I choose to put out greatness.",
  "Every day I am becoming the person I was always meant to be.",
  "I nourish my body, sharpen my mind, and strengthen my spirit daily.",
  "I draw from an unending well of courage and resilience within me.",
  "I choose to see the beauty and opportunity in every situation.",
  "I am proud of myself, my achievements, and the life I am creating.",
  "Challenges make me stronger. I welcome them with an open heart.",
];

// Returns a consistent affirmation per calendar day using the day-of-year
export function getDailyAffirmation() {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now - start;
  const oneDay = 1000 * 60 * 60 * 24;
  const dayOfYear = Math.floor(diff / oneDay);
  return affirmations[dayOfYear % affirmations.length];
}
